version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      wazuh-net:
        ipv4_address: 172.23.0.5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      wazuh-net:
        ipv4_address: 172.23.0.15

  filebeat:
    build:
      context: .
      dockerfile: Dockerfile.filebeat
    container_name: filebeat
    user: root
    volumes:
      - ./suricata/logs:/var/log/suricata:ro
    depends_on:
      - elasticsearch
    networks:
      wazuh-net:
        ipv4_address: 172.23.0.10

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    cap_add:
      - NET_ADMIN
    command: -c /etc/suricata/suricata.yaml -i eth0 --init-errors-fatal
    network_mode: "container:victim"
    volumes:
      - ./suricata/logs:/var/log/suricata
      - ./suricata/rules:/etc/suricata/rules
      - ./suricata/suricata.yaml:/etc/suricata/suricata.yaml

  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    tty: true
    command: sleep infinity
    networks:
      wazuh-net:
        ipv4_address: 172.23.0.8

  victim:
    image: ubuntu
    container_name: victim
    tty: true
    command: /bin/bash -c "apt update && apt install -y iproute2 net-tools iputils-ping && sleep infinity"
    networks:
      wazuh-net:
        ipv4_address: 172.23.0.9

networks:
  wazuh-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
